
package:
  name: difi
  version: "{{ version }}"

source:
  git_url: "https://github.com/moeyensj/difi.git"
  git_tag: "v{{ version }}"

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=45
    - wheel
    - setuptools_scm >=6.0
  run:
    - python >=3.8
    - numba
    - numpy
    - pandas
    - pytest
    - pytest-cov
    - pytest-benchmark
    - pre-commit

build:
  noarch: python
  script: pip install .

test:
  imports:
    - difi

about:
  home: https://github.com/moeyensj/difi
  license: BSD-3 Clause
  license_file: LICENSE.md
