name: conda - Build Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-lint-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
      - name: Get git tags
        run:  git fetch --prune --unshallow --tags
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: "difi"
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Build and install
        run: pip install .[dev]
      - name: Lint
        run: pdm lint
      - name: Test
        run: pdm test